services:
  - type: web
    name: EdupredictAI
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && python backend/train_model.py
    startCommand: gunicorn --chdir backend app:app --workers 2 --threads 4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
